.\" $NiH: dccsend.mdoc,v 1.2 2003/05/14 08:22:41 wiz Exp $
.\"
.\" Copyright (c) 2003 Thomas Klausner.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above
.\"    copyright notice, this list of conditions and the following
.\"    disclaimer in the documentation and/or other materials provided
.\"    with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior
.\"    written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THOMAS KLAUSNER ``AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
.\" USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.Dd April 7, 2003
.Dt DCCSEND 1
.Os
.Sh NAME
.Nm dccsend
.Nd send a file to a MIRC /dccserver
.Sh SYNOPSIS
.Nm ""
.Op Fl hv
.Op Fl n Ar nickname
.Op Fl p Ar port
.Op Fl r Ar remotenick
.Ar host
.Ar filename
.Sh DESCRIPTION
.Nm
sends a file to remote host running a MIRC /dccserver or
.Xr dccserver 1 .
The
.Ar host
argument specifies the name or IP of the server where
.Xr dccserver 1
is running, and the
.Ar filename
argument denotes the name of the local file to send to the remote host.
You can get the hostname or IP of a fellow IRCer by doing
.Dq /whois remotenick ,
the first line will probably contain
.Dq user@example.org
or
.Dq user@127.0.0.1 .
.Pp
Supported options:
.Bl -tag -width XrXremotenickXX
.It Fl h
Display a short help message.
.It Fl n Ar nickname
Set nickname used in handshake to
.Ar nickname .
Should be the same nickname that you use on IRC, otherwise some
servers might complain and close the connection.
Defaults to
.Dq dccsend .
.It Fl p Ar port
Denote
.Ar port
on which the remote
.Xr dccserver 1
is listening.
Defaults to 59, since that is MIRC's default port.
.It Fl r Ar remotenick
Expected nickname on the remote side.
.It Fl v
Display program name and version number.
.El
.Sh EXAMPLES
Typical usage:
.Pp
.Bd -literal -offset indent
dccsend -n yournick example.org /path/to/file
.Ed
.Sh AUTHORS
.Nm
was written by
.An Thomas Klausner Aq wiz@danbala.tuwien.ac.at .
.Sh BUGS
There are no timeouts, just interrupt and try again.
The protocol supports resuming automatically.
