.TH "DCCSEND" "1" "January 20, 2012" "NiH" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBdccsend\fR
\- send a file to a mIRC /dccserver
.SH "SYNOPSIS"
.HP 8n
\fBdccsend\fR
[\fB\-hv\fR]
[\fB\-n\fR\ \fInickname\fR]
[\fB\-p\fR\ \fIport\fR]
[\fB\-r\fR\ \fIremotenick\fR]
\fIhost\fR
\fIfilename\fR
.SH "DESCRIPTION"
\fBdccsend\fR
sends a file to remote host running a mIRC /dccserver or
dccserver(1).
The
\fIhost\fR
argument specifies the name or IP of the server where
dccserver(1)
is running, and the
\fIfilename\fR
argument denotes the name of the local file to send to the remote host.
You can get the hostname or IP of a fellow IRCer by doing
\(lq/whois remotenick\(rq,
the first line will probably contain
\(lquser@example.org\(rq
or
\(lquser@127.0.0.1\(rq.
.PP
Supported options:
.TP 17n
\fB\-h\fR
Display a short help message.
.TP 17n
\fB\-n\fR \fInickname\fR
Set nickname used in handshake to
\fInickname\fR.
Should be the same nickname that you use on IRC, otherwise some
servers might complain and close the connection.
Defaults to
\(lqdccsend\(rq.
.TP 17n
\fB\-p\fR \fIport\fR
Denote
\fIport\fR
on which the remote
dccserver(1)
is listening.
Defaults to 59, since that is mIRC's default port.
.TP 17n
\fB\-r\fR \fIremotenick\fR
Expected nickname on the remote side.
.TP 17n
\fB\-v\fR
Display program name and version number.
.SH "EXAMPLES"
Typical usage:
.nf
.sp
.RS 6n
dccsend -n yournick example.org /path/to/file
.RE
.fi
.SH "SEE ALSO"
dccserver(1)
.SH "AUTHORS"
\fBdccsend\fR
was written by
Thomas Klausner <\fItk@giga.or.at\fR>.
.SH "BUGS"
There are no timeouts, just interrupt and try again.
The protocol supports resuming automatically.
